basePath: /
definitions:
  admin.updateKReceiptDeductResponse:
    properties:
      kReceipt:
        type: number
    type: object
  admin.updatePersonalDeductResponse:
    properties:
      personalDeduction:
        type: number
    type: object
  admin.updateTaxDeductRequest:
    properties:
      amount:
        minimum: 0
        type: number
    type: object
  github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-array_validator_Field:
    properties:
      code:
        type: string
      errors:
        items:
          $ref: '#/definitions/validator.Field'
        type: array
      message:
        type: string
    type: object
  github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string:
    properties:
      code:
        type: string
      errors:
        type: string
      message:
        type: string
    type: object
  tax.allowance:
    properties:
      allowanceType:
        example: donation
        type: string
      amount:
        example: 200000
        minimum: 0
        type: number
    required:
    - allowanceType
    type: object
  tax.taxCSV:
    properties:
      tax:
        type: number
      taxRefund:
        type: number
      totalIncome:
        type: number
    type: object
  tax.taxCalculateRequest:
    properties:
      allowances:
        items:
          $ref: '#/definitions/tax.allowance'
        type: array
        uniqueItems: true
      totalIncome:
        example: 500000
        minimum: 0
        type: number
      wht:
        example: 25000
        minimum: 0
        type: number
    required:
    - allowances
    type: object
  tax.taxCalculateResponse:
    properties:
      tax:
        type: number
      taxLevel:
        items:
          $ref: '#/definitions/tax.taxLevel'
        type: array
      taxRefund:
        type: number
    type: object
  tax.taxLevel:
    properties:
      level:
        type: string
      tax:
        type: number
    type: object
  tax.texes:
    properties:
      texes:
        items:
          $ref: '#/definitions/tax.taxCSV'
        type: array
    type: object
  validator.Field:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
  description: BasicAuth protects our entity endpoints.
  title: Assessment Tax API
  version: "1.0"
paths:
  /admin/deductions/k-receipt:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/admin.updateTaxDeductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/admin.updateKReceiptDeductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-array_validator_Field'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
      security:
      - BasicAuth: []
      tags:
      - admin
  /admin/deductions/personal:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/admin.updateTaxDeductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/admin.updatePersonalDeductResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-array_validator_Field'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
      security:
      - BasicAuth: []
      tags:
      - admin
  /tax/calculations:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tax.taxCalculateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/tax.taxCalculateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-array_validator_Field'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
      tags:
      - tax
  /tax/calculations/upload-csv:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ' '
        in: formData
        name: taxFile
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/tax.texes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-array_validator_Field'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github.com_wit-switch_assessment-tax_internal_handler_http.ResponseError-string'
      tags:
      - tax
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
